# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

pr:
- azure-pipeline-test

job: 'Unit test'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
  displayName: 'Use Python 3.6'

- script: |
    python -m pip install --upgrade pip
    pip install Cython numpy
    pip install -e .
  displayName: 'Install packages and ClusterSheep'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
